# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Snap_Point
                                 A QGIS plugin
 This plugin snaps a selected point to the closest point of a feature from a defined layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-09-20
        copyright            : (C) 2022 by Valerio Pinna
        email                : pinnavalerio@yahoo.co.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Snap_Point class from file Snap_Point.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .snap_point import Snap_Point
    return Snap_Point(iface)
