# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Snap_Point
                                 A QGIS plugin
 This plugin snaps a selected point to the closest point of a feature from a defined layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-09-20
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Valerio Pinna
        email                : pinnavalerio@yahoo.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import sys
import subprocess
from math import sqrt
from qgis.PyQt.QtCore import *

from qgis.PyQt.QtGui import *
from PyQt5.QtGui import *
from qgis.PyQt.QtWidgets import *
from qgis.PyQt import uic
from PyQt5.QtWidgets import QMessageBox
from qgis.core import *
                       
from qgis.utils import iface


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
import os.path

Ui_ConfigureSnapPointDialogBase = uic.loadUiType(os.path.join(os.path.dirname(__file__), 'configuresnappoint.ui'))[0]


def point_max_distance_value():
    settings = QSettings()
    return settings.value('point_max_distance_value', type=float)

def setPointMaxDistance(point_max_distance):
    settings = QSettings()
    return settings.setValue('point_max_distance_value', point_max_distance)
    
def point_polygon_layer_value():
    settings = QSettings()
    return settings.value('point_polygon_layer_value')

def setPointPolygonLayer(point_polygon_layer):
    settings = QSettings()
    return settings.setValue('point_polygon_layer_value', point_polygon_layer)



class ConfigureSnapPointsDialog (QDialog, Ui_ConfigureSnapPointDialogBase):
    def __init__(self, parent):
        super().__init__()
        self.iface = parent
        self.setupUi(self)
        
        #update the dialog with the last entered value
        self.distance_doubleSpinBox.setValue(point_max_distance_value())
        point_max_distance = point_max_distance_value()
  
        layers_list = QgsProject.instance().mapLayers()
        
        if len(layers_list)!= 0:                  
            point_list = []            
            for lay in layers_list.values():
                if lay.type() == QgsVectorLayer.VectorLayer:
                    if lay.wkbType() == 1: #point
                        point_list.append(lay)
                        
   
       
        self.polygon_mMapLayerComboBox.setFilters(QgsMapLayerProxyModel.HasGeometry )
        self.polygon_mMapLayerComboBox.setExceptedLayerList(point_list)      

        
        if len(layers_list)!= 0: 
            if not point_polygon_layer_value():
                return self.dontdonothing()
                
            else:
                self.polygon_mMapLayerComboBox.setLayer(point_polygon_layer_value())
                point_polygon_layer = point_polygon_layer_value() 
    
    
    def dontdonothing(self):
            pass
   

class Snap_Point:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.canvas = iface.mapCanvas()
        self.iface = iface
        self.toolButton = QToolButton()
        self.toolButton.setMenu(QMenu())
        self.toolButton.setPopupMode(QToolButton.MenuButtonPopup)
        self.toolBtnAction = self.iface.addToolBarWidget(self.toolButton)
        
        
        
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        
        
        
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Snap_Point_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Snap Point')

        self.iface.currentLayerChanged["QgsMapLayer*"].connect(self.toggle)

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Snap_Point', message)


    def initGui(self):    
        self.actionRun = QAction(
          QIcon(os.path.join(os.path.dirname(__file__), "icons/snap_point_icon.png")),
          self.tr('Snap a point to the closest feature in the selected layer'),
          self.iface.mainWindow(),
        )      
        self.actionRun.setEnabled(False)
        self.iface.addPluginToMenu(self.tr(u'&Snap Point'), self.actionRun)
        m = self.toolButton.menu()
        m.addAction(self.actionRun)
        self.toolButton.setDefaultAction(self.actionRun)
        self.actionRun.triggered.connect(self.run)
        self.actionConfigure = QAction(
          QIcon(os.path.join(os.path.dirname(__file__), "icons/snap_point_configure_icon.png")),
          self.tr('Configure'),
          self.iface.mainWindow()
        )
        self.iface.registerMainWindowAction(self.actionConfigure, "")
        self.actionConfigure.setToolTip(self.tr('Configure the snapping point tool'))
        m.addAction(self.actionConfigure)
        self.iface.addPluginToMenu(self.tr(u'&Snap Point'), self.actionConfigure)
        self.actionConfigure.triggered.connect(self.configure)
      
 
    def unload(self):
       for action in [self.actionRun,self.actionConfigure]:
           self.iface.removePluginMenu(self.tr(u'&Snap Point'),action)
           self.iface.removeToolBarIcon(action)
           self.iface.unregisterMainWindowAction(action)

       self.iface.removeToolBarIcon(self.toolBtnAction)

    def enable_icon(self):
        self.actionRun.setEnabled(True)

    def run(self):
        settings = QSettings
        point_max_distance = point_max_distance_value()      
        point_polygon_layer= point_polygon_layer_value()
        
        if point_polygon_layer == None:
            iface.messageBar().pushMessage('Snap Point Plugin:', 'No snapping layer selected. Plese configure the plugin and retry', level=Qgis.Warning)   
            return self.dontdonothing()          
        
        else:
            point_polygon_layer_name = point_polygon_layer.name()
            
            print ('The point_polygon_layer_name is ',point_polygon_layer_name)
      
            polylayer = QgsProject.instance().mapLayersByName(point_polygon_layer_name)[0]
            points = iface.activeLayer()
            if points is not None:
                provider = polylayer.dataProvider()

                #spatial index for polygonal layer (Archaeological Features)
                spIndex = QgsSpatialIndex() #create spatial index object
                polylayer.removeSelection()
                feat = QgsFeature()
                fit = provider.getFeatures() #gets all features in layer


                #selected points on DP
                selected_DP = []

                for p_feat in points.selectedFeatures():
                    old_DP_point = p_feat.geometry().asPoint()
                    old_DP_point_Wkt = p_feat.geometry().asWkt()
                    selected_DP.append(old_DP_point)
                    old_DP_point_id = [p_feat.id()]
                    
                    
                    # insert features to index
                    while fit.nextFeature(feat):
                        spIndex.insertFeature(feat)
                    pt = selected_DP[0]
                    
                    # QgsSpatialIndex.nearestNeighbor (QgsPoint point, int neighbors)
                    nearestIds = spIndex.nearestNeighbor(pt,1) # we need only one neighbour
                    print (nearestIds)
                    single_nearestIds = []
                    if len(nearestIds) == 1:
                        single_nearestIds = nearestIds
                    if len(nearestIds) > 1:
                        single_nearestIds.append(nearestIds[-1])
                    print (single_nearestIds)
                    #select nearest polygon by id
                    polylayer.select(nearestIds)
                    for feature in polylayer.selectedFeatures():
                        g_poly = feature.geometry()

                        if polylayer.geometryType() == 1: #line
                            calc_new_geom = g_poly.closestVertex(old_DP_point)
                            new_geom = calc_new_geom[0]
                            sqrDist = calc_new_geom[4]
                            
                        if polylayer.geometryType() == 2: #polygon
                            calc_new_geom = g_poly.closestSegmentWithContext(old_DP_point)
                            new_geom = calc_new_geom[1]
                            sqrDist = calc_new_geom[0]
                            

                        real_distance = sqrt(sqrDist)
                        print (real_distance)
                        polylayer.removeSelection()
                        if real_distance <= point_max_distance:
                            new_pt_wtk = new_geom.asWkt()
                            points.startEditing()
                            points.beginEditCommand("Snap Drawing Point")
                            points.selectByIds(old_DP_point_id)
                            new_geometry = QgsGeometry.fromWkt(new_pt_wtk)
                            points.changeGeometry(old_DP_point_id[0], new_geometry)

                            # Save the changes in the buffer 
                            points.triggerRepaint()
                            #iface.mapCanvas().refresh()
                            
                            points.endEditCommand()
                        else:
                            iface.messageBar().pushMessage('Snap Point Plugin:', 'No features available within the set distance range', level=Qgis.Info)   
                            polylayer.removeSelection()
                            return self.dontdonothing() 

        
    def configure(self):
        dlg = ConfigureSnapPointsDialog(self.iface)
        dlg.exec_()
        if dlg.result():
            
            
            point_max_distance = dlg.distance_doubleSpinBox.value()
            setPointMaxDistance(point_max_distance)

            
            point_polygon_layer = dlg.polygon_mMapLayerComboBox.currentLayer() 
            setPointPolygonLayer(point_polygon_layer)


    def dontdonothing(self):
            pass

    
    def toggle(self):
        _point = QgsWkbTypes.PointGeometry  # QGis3
        

        # QgsMessageLog.logMessage("Toggle")
        layer = self.canvas.currentLayer()
        # Decide whether the plugin button/menu is enabled or disabled
        if layer is not None:
            if layer.type() == QgsMapLayer.VectorLayer:
                try:
                # disconnect, will be reconnected
                    layer.editingStarted.disconnect(self.toggle)
                except:
                    pass
                try:
                    # when it becomes active layer again
                    layer.editingStopped.disconnect(self.toggle)
                except:
                    pass
                
                if layer.geometryType() == _point:
                    self.actionConfigure.setEnabled(True)
                    self.actionRun.setEnabled(True)
                   
                else:
                    self.actionConfigure.setEnabled(False)
                    self.actionRun.setEnabled(False)
                